### ISSUE TITLE
Issue in build the Repo. [needed by 'bme680_esp.elf', missing and no known rule to make it]

### ISSUE THREAD

**Issue by horsemann07** [mjaakkol/bme680_esp_idf#2]
Hello @mjaakkol 

I m trying to run your repo on esp-idf 4.2,
I make the changes in the CMake file which is in the bm680 folder as per your instruction.
When I m building, it shows some error

Error:
`-- Configuring done
-- Generating done
-- Build files have been written to: /home/horsemann/Desktop/WorkSpace/esp-version-4.2/esp-idf/examples/BME680/build
Running ninja in directory /home/horsemann/Desktop/WorkSpace/esp-version-4.2/esp-idf/examples/BME680/build
Executing "ninja all"...
ninja: error: '../bme680/algo/normal_version/bin/esp32/libalgobsec.a', needed by 'bme680_esp.elf', missing and no known rule to make it
ninja failed with exit code 1
`

Can you help me with this?
Thanks in advance.

**Comment by mjaakkol** [comment]
It looks like CMake is not finding the library file. Are you sure that the directory hierarchy under BME680 folder is in format algo/normal_version/bin/esp32/libalgobsec.a?

**Comment by horsemann07** [comment]
Hello @mjaakkol 
Thanks for the fast reply.

No. the format is /algo/normal_version/bin/esp/esp32/libalgobsec.a which I changed now in cmake files.

Now the issue is gone.
Thank you for the help.
